name: wxyz-demo

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - dask
  - dask >=0.18.2
  - dask-ml
  - distributed
  - importnb
  - ipympl
  - ipywidgets
  - jsonpointer
  - jupyterlab >=0.35,<0.36
  - lime
  - nodejs >=8.11,<9
  - pip
  - py-xgboost
  - pyld
  - python >=3.7,<3.8
  - pyyaml
  - scikit-image
  - scikit-learn
  - scikit-mdr
  - skrebate
  - tornado <6
  - tpot
  - xgboost
  - matplotlib
  - umap-learn
  - cycler
  - pip:
      - yellowbrick
      - json-e
